export const COUNTRY_TO_CODE: Record<string, string> = {
  'Brazil': 'br',
  'Argentina': 'ar',
  'Uruguay': 'uy',
  'Paraguay': 'py',
  'Ecuador': 'ec',
  'Peru': 'pe',
  'Chile': 'cl',
  'Colombia': 'co',
  'Venezuela': 've',
  'Bolivia': 'bo',
  'Germany': 'de',
  'France': 'fr',
  'Spain': 'es',
  'Italy': 'it',
  'Netherlands': 'nl',
  'Portugal': 'pt',
  'Belgium': 'be',
  'England': 'gb-eng',
  'Denmark': 'dk',
  'Croatia': 'hr',
  'Switzerland': 'ch',
  'Serbia': 'rs',
  'Poland': 'pl',
  'Austria': 'at',
  'Ukraine': 'ua',
  'Sweden': 'se',
  'Hungary': 'hu',
  'Scotland': 'gb-sct',
  'Wales': 'gb-wls',
  'Turkey': 'tr',
  'Czech Republic': 'cz',
  'Slovakia': 'sk',
  'Romania': 'ro',
  'Greece': 'gr',
  'Norway': 'no',
  'Slovenia': 'si',
  'United States': 'us',
  'Mexico': 'mx',
  'Canada': 'ca',
  'Costa Rica': 'cr',
  'Panama': 'pa',
  'Jamaica': 'jm',
  'Honduras': 'hn',
  'El Salvador': 'sv',
  'Japan': 'jp',
  'South Korea': 'kr',
  'Australia': 'au',
  'Saudi Arabia': 'sa',
  'Iran': 'ir',
  'Qatar': 'qa',
  'United Arab Emirates': 'ae',
  'Iraq': 'iq',
  'Oman': 'om',
  'Morocco': 'ma',
  'Senegal': 'sn',
  'Nigeria': 'ng',
  'Egypt': 'eg',
  'Tunisia': 'tn',
  'Algeria': 'dz',
  'Cameroon': 'cm',
  'Ghana': 'gh',
  'Ivory Coast': 'ci',
  'Burkina Faso': 'bf',
  'Mali': 'ml',
  'South Africa': 'za',
  'DR Congo': 'cd',
  'New Zealand': 'nz',
  'Fiji': 'fj',
  'Tahiti': 'pf',
  'Solomon Islands': 'sb',
}

export const FIFA_RANKINGS: Record<string, number> = {
  'Argentina': 1,
  'France': 2,
  'Brazil': 3,
  'England': 4,
  'Belgium': 5,
  'Netherlands': 6,
  'Portugal': 7,
  'Spain': 8,
  'Italy': 9,
  'Croatia': 10,
  'Germany': 11,
  'United States': 12,
  'Mexico': 13,
  'Uruguay': 14,
  'Colombia': 15,
  'Denmark': 16,
  'Japan': 17,
  'Switzerland': 18,
  'Morocco': 19,
  'Senegal': 20,
  'Peru': 21,
  'Sweden': 22,
  'Poland': 23,
  'Ukraine': 24,
  'Wales': 25,
  'South Korea': 26,
  'Canada': 27,
  'Serbia': 28,
  'Austria': 29,
  'Hungary': 30,
  'Ecuador': 31,
  'Saudi Arabia': 32,
  'Nigeria': 33,
  'Australia': 34,
  'Egypt': 35,
  'Iran': 36,
  'Tunisia': 37,
  'Algeria': 38,
  'Cameroon': 39,
  'Ivory Coast': 40,
  'Ghana': 41,
  'Costa Rica': 42,
  'Paraguay': 43,
  'Slovakia': 44,
  'Norway': 45,
  'Scotland': 46,
  'Chile': 47,
  'Panama': 48,
  'Turkey': 49,
  'Romania': 50,
  'Greece': 51,
  'Czech Republic': 52,
  'Jamaica': 53,
  'Bolivia': 54,
  'Venezuela': 55,
  'Honduras': 56,
  'El Salvador': 57,
  'New Zealand': 58,
  'Slovenia': 59,
  'Burkina Faso': 60,
  'Mali': 61,
  'DR Congo': 62,
  'South Africa': 63,
  'Fiji': 64,
  'Tahiti': 65,
  'Solomon Islands': 66,
  'Iraq': 67,
  'United Arab Emirates': 68,
  'Oman': 69,
  'Qatar': 70,
}

export const GROUPS: Record<string, string[]> = {
  'A': ['United States', 'Canada', 'Mexico', 'Panama'],
  'B': ['Argentina', 'Peru', 'Chile', 'Bolivia'],
  'C': ['Brazil', 'Colombia', 'Paraguay', 'Venezuela'],
  'D': ['England', 'Denmark', 'Serbia', 'Slovenia'],
  'E': ['France', 'Netherlands', 'Austria', 'Hungary'],
  'F': ['Germany', 'Spain', 'Italy', 'Switzerland'],
  'G': ['Portugal', 'Belgium', 'Croatia', 'Turkey'],
  'H': ['Uruguay', 'Ecuador', 'Costa Rica', 'Jamaica'],
  'I': ['Japan', 'South Korea', 'Australia', 'New Zealand'],
  'J': ['Morocco', 'Senegal', 'Nigeria', 'Egypt'],
  'K': ['Ivory Coast', 'Ghana', 'Cameroon', 'Mali'],
  'L': ['Saudi Arabia', 'Iran', 'Tunisia', 'Algeria'],
}
